# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tianxiang Han's Blog
email: 18610611028@163.com
description: > # this means to ignore newlines until "baseurl:"
  Everybody wants something, just a little more
  We're makin a living, and what we're livin for
  A rich man or a poor man, a pawn or a king
  You can live on the street, you can rule the whole world
  But you don't mean one damn thing
  What do you got, if you aint got love
baseurl: "/myblog" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: losthan
github_username:  losthan

# Build settings
markdown: kramdown
